name: FTP Deploy

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@3.1
        with:
          server: ftp://your-ftp-server.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
